spring.application.name=unsolved_frontend

server.domain=127.0.0.1

server.port=80

# Properties ?? - Thymeleaf ??
spring.thymeleaf.enabled=true
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html